[build-system]
requires = ["setuptools >= 80.9.0"]
build-backend = "setuptools.build_meta"


[project]
name = "StrictMock"
version = "0.6.6"
requires-python = ">=3.11"
description = "Highly Deterministic Mocking"
license = "BSD-3-Clause"
readme = "README.md"
keywords = ["mock", "unittest"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Testing :: Mocking",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = []

[project.optional-dependencies]
testing = [
    "pytest"
]

[project.entry-points."pytest11"]
strict-mock = "strict_mock.plugin"

[tool.mypy]
check_untyped_defs = true

[tool.coverage.run]
omit = ["strict_mock/plugin.py"]
