from ..analysis import MockContainerError as MockContainerError, Param as Param, ParamList as ParamList, TypeData as TypeData
from typing import Any, Callable

def _non_keyed(name: str, r_type: Any) -> Callable: ...
def _keyed(name: str, r_type: Any) -> Callable: ...
def _del(mock, key: Any) -> None: ...
def _set(mock, key: Any, value: Any) -> None: ...

container_dunders: dict[str, Callable]
