from ..analysis import MockContextManagerError as MockContextManagerError, MockError as MockError, Param as Param, ParamIgnore as ParamIgnore, ParamList as ParamList, TypeData as TypeData
from typing import Any, Callable

def _enter(mock) -> TypeData: ...
def cm_enter(mock) -> Any: ...
def _exit(mock, exc_type, exc_val, exc_tb) -> tuple[str | None, TypeData]: ...
def cm_exit(mock, exc_type, exc_val, exc_tb) -> bool | None: ...

cm_dunders: dict[str, Callable]
