from ..analysis import Param as Param, ParamIgnore as ParamIgnore, ParamList as ParamList, TypeData as TypeData
from _typeshed import Incomplete

def _event_compare(name: str): ...
def _event_no_arg(name: str, r_type: type): ...
def _event_repr(name: str): ...
def _format(mock, format_spec: str) -> str: ...

default_dunders: Incomplete
