from _typeshed import Incomplete
from strict_mock.analysis import Actual as Actual, ErrorExpected as ErrorExpected, Expected as Expected, MockCreationError as MockCreationError, MockError as MockError, TypeData as TypeData, TypeIgnore as TypeIgnore
from strict_mock.implementations.formatter import DefaultFormatter as DefaultFormatter, IReportFormatter as IReportFormatter
from typing import Any, NoReturn

class Events:
    _formatter: Incomplete
    _expected: list[Expected]
    _actual: list[Actual]
    _type_data: list[TypeData | None]
    _error_type: type[MockError]
    _error_reported: bool
    _mocks: dict[str, Any]
    def __init__(self, expected: list[Expected] | None = None, formatter: IReportFormatter | None = None) -> None: ...
    def __iter__(self): ...
    def _add_mock(self, name, mock) -> None: ...
    def _check_for_mock(self, mock: Any, expected: Expected, index: int) -> Expected: ...
    def _assert_all_calls(self, mock) -> bool: ...
    def _set_error_type(self, error_type: type[MockError]): ...
    def _report_errors(self, mock) -> NoReturn: ...
    def add_actual(self, mock, call_name: str, type_data: TypeData, *args, **kwargs) -> Any: ...
    def _has_errors(self) -> bool: ...
