from strict_mock.analysis import Actual as Actual, ErrorExpected as ErrorExpected, Expected as Expected, MockCreationError as MockCreationError, MockError as MockError, TypeData as TypeData, TypeIgnore as TypeIgnore
from strict_mock.implementations.formatter import DefaultFormatter as DefaultFormatter, IReportFormatter as IReportFormatter
from typing import Any

class Events:
    def __init__(self, expected: list[Expected] | None = None, formatter: IReportFormatter | None = None) -> None: ...
    def __iter__(self): ...
    def add_actual(self, mock, call_name: str, type_data: TypeData, *args, **kwargs) -> Any: ...
