from _typeshed import Incomplete
from dataclasses import dataclass
from strict_mock.analysis import MockPropertyError as MockPropertyError, Param as Param, ParamList as ParamList, TypeData as TypeData
from types import ModuleType
from typing import Any, Callable

_dsc = dict[str, Callable]

@dataclass
class Prop:
    name: str
    type: type[Any]
    getter: bool = ...
    setter: bool = ...
    deleter: bool = ...
    is_active: bool = ...

class Properties:
    _spec: Incomplete
    _properties: dict[str, Prop]
    def __init__(self, spec: type[Any] | Callable | ModuleType) -> None: ...
    def get_properties_with_setters(self) -> dict[str, Prop]: ...
    def _get_prop_type(self, obj: Any) -> type[Prop]: ...
    def add_properties(self, spec_mocked: _dsc, props: list[Prop] | None = None) -> _dsc: ...
    def create_prop(self, prop: Prop) -> Any: ...
    def _create_getter(self, prop: Prop) -> Callable | None: ...
    def _create_setter(self, prop: Prop) -> Callable | None: ...
    def _create_deleter(self, prop: Prop) -> Callable | None: ...
