from dataclasses import dataclass

@dataclass
class MockData:
    filename: str
    test_name: str
    mock_name: str
    line_number: int

_counter: int
_registry: dict[int, MockData]
_atexit_armed: bool
_externally_managed: bool

def register_mock(mock_data: MockData) -> int: ...
def deregister_mock(mock_id: int) -> None: ...
def get_unasserted_mocks() -> list[MockData]: ...
def clear_mocks() -> None: ...
def _leak_report() -> str: ...
def assert_no_leaked_mocks() -> None: ...
def set_externally_managed() -> None: ...
def _arm_atexit_leak_check() -> None: ...
def _disarm_atexit_leak_check() -> None: ...
def _atexit_leak_check() -> None: ...
