from dataclasses import dataclass

@dataclass
class MockData:
    filename: str
    test_name: str
    mock_name: str
    line_number: int

def register_mock(mock_data: MockData) -> int: ...
def deregister_mock(mock_id: int) -> None: ...
def get_unasserted_mocks() -> list[MockData]: ...
def clear_mocks() -> None: ...
def assert_no_leaked_mocks() -> None: ...
def set_externally_managed() -> None: ...
