from .errors import MockTypeError as MockTypeError
from _typeshed import Incomplete
from typing import Any

_SAFE_TYPE_STRING: Incomplete
Empty: Incomplete

class CheckType:
    _imported: dict[str, type]
    def __init__(self) -> None: ...
    @staticmethod
    def _qualified_name(t: Any) -> tuple[str | None, str | None]: ...
    def import_type(self, *types: Any) -> CheckType: ...
    def import_from_globals(self, globals_dict: dict) -> CheckType: ...
    def __repr__(self) -> str: ...
    def __call__(self, t: type | str, v: Any) -> bool: ...
    @staticmethod
    def _find_missing(types: list[str], all_set: set) -> None: ...
    @staticmethod
    def _parse_union(type_string: str) -> tuple[str, list[str]]: ...
    def _check(self, t: type, v: Any) -> bool: ...
    @staticmethod
    def _check_arg_count(name: str, required: int, args: tuple[Any, ...]): ...
    def _dict(self, t: type, v: Any) -> bool: ...
    def _frozenset(self, t: type, v: Any) -> bool: ...
    def _list(self, t: type, v: Any) -> bool: ...
    def _set(self, t: type, v: Any) -> bool: ...
    def _tuple(self, t: type, v: Any) -> bool: ...
    def _type(self, t: type, v: Any) -> bool: ...
    def _Union(self, t: type, v: Any) -> bool: ...

class ImportedTypes:
    _types: Incomplete
    _check_type: CheckType | None
    def __init__(self, *types: Any) -> None: ...
    @property
    def check_type(self) -> CheckType: ...
