from .errors import MockTypeError as MockTypeError
from _typeshed import Incomplete
from typing import Any

Empty: Incomplete

class CheckType:
    def __init__(self) -> None: ...
    def import_type(self, *types: Any) -> CheckType: ...
    def import_from_globals(self, globals_dict: dict) -> CheckType: ...
    def __call__(self, t: type | str, v: Any) -> bool: ...

class ImportedTypes:
    def __init__(self, *types: Any) -> None: ...
    @property
    def check_type(self) -> CheckType: ...
