__all__ = ['MockCallableError', 'MockClassError', 'MockContainerError', 'MockContextManagerError', 'MockCreationError', 'MockError', 'MockIteratorError', 'MockMethodError', 'MockPropertyError', 'MockTypeError']

class MockError(Exception): ...
class MockCallableError(MockError): ...
class MockClassError(MockError): ...
class MockContainerError(MockError): ...
class MockContextManagerError(MockError): ...
class MockCreationError(MockError, AttributeError): ...
class MockIteratorError(MockError): ...
class MockMethodError(MockError): ...
class MockPropertyError(MockError): ...
class MockTypeError(MockError): ...
