from .actual import Actual as Actual
from .utility import TypeIgnore as TypeIgnore, ValueIgnore as ValueIgnore, stringify as stringify
from enum import Enum
from typing import Any

class _ReturnType(Enum):
    kNone = 0
    kValue = 1
    kSelf = 2
    kSelfIgnore = 3

class Expected(Actual):
    def __init__(self, name: str, *args, **kwargs) -> None: ...
    def returns_value(self, value: Any) -> Expected: ...
    def returns_mock(self, name: str | None = None, ignore_type: bool = False) -> Expected: ...
    def raises_error(self, error: Exception) -> Expected: ...
    def stop_iteration(self) -> Expected: ...
    def compare_actual(self, actual: Actual) -> bool: ...
    def report(self) -> str: ...
