from .actual import Actual as Actual
from .errors import MockCreationError as MockCreationError
from .utility import TypeIgnore as TypeIgnore, ValueIgnore as ValueIgnore, stringify as stringify
from _typeshed import Incomplete
from enum import Enum
from typing import Any

class _ReturnType(Enum):
    kNone = 0
    kValue = 1
    kSelf = 2
    kSelfIgnore = 3

class Expected(Actual):
    _return_value: Any
    _returns_type: _ReturnType
    _error: Exception | None
    _nomenclature: str
    def __init__(self, name: str, *args, **kwargs) -> None: ...
    def __eq__(self, other: Any) -> bool: ...
    def returns_value(self, value: Any) -> Expected: ...
    def returns_mock(self, name: str | None = None, ignore_type: bool = False) -> Expected: ...
    def _is_mock(self) -> bool: ...
    def _get_mock_name(self) -> str | None: ...
    def _check_for_self(self, mock: Any) -> None: ...
    def raises_error(self, error: Exception) -> Expected: ...
    def stop_iteration(self) -> Expected: ...
    def stop_async_iteration(self) -> Expected: ...
    def _get_return_value(self) -> Any: ...
    def compare_actual(self, actual: Actual) -> bool: ...
    def report(self, indent: str = '') -> str: ...
    def _report_mock_fix(self, mock_name: str) -> str: ...

class ErrorExpected(Expected):
    _fix: Incomplete
    _expected: Incomplete
    _other: Incomplete
    def __init__(self, name: str, fix: str, expected: Expected | None = None, other: Any = None) -> None: ...
    def compare_actual(self, actual: Actual) -> bool: ...
    def report(self, indent: str = '') -> str: ...
