import inspect
from .utility import name_with_prefix as name_with_prefix, stringify as stringify, type_name as type_name
from _typeshed import Incomplete
from dataclasses import dataclass, field
from typing import Any

_empty: Incomplete
_ip = inspect.Parameter

def get_default_kind(): ...

@dataclass
class Param:
    name: str = ...
    type: Any = ...
    default: Any = ...
    kind: Any = field(default_factory=get_default_kind)
    checked: bool = ...
    index: int = ...
    @property
    def is_positional(self) -> bool: ...
    @property
    def is_keyword(self) -> bool: ...
    @property
    def is_variadic(self) -> bool: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: Any) -> bool: ...
    def as_param(self) -> str: ...

@dataclass
class ParamValue(Param):
    value: Any = ...
    def as_param(self) -> str: ...

@dataclass
class ParamExtra(Param):
    extra: Any = ...
    def as_param(self) -> str: ...

@dataclass
class ParamDefault(Param):
    def as_param(self) -> str: ...

class ParamIgnore(Param):
    def __init__(self, name: str) -> None: ...
    def as_param(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other): ...
