from .check_type import CheckType as CheckType
from .param import Param as Param, ParamDefault as ParamDefault, ParamExtra as ParamExtra, ParamValue as ParamValue
from .param_list import ParamList as ParamList
from .utility import IValueEqual as IValueEqual, TypeIgnore as TypeIgnore, ValueIgnore as ValueIgnore, stringify as stringify, type_name as type_name
from _typeshed import Incomplete
from typing import Any

_empty: Incomplete

class TypeData:
    name: Incomplete
    _params: Incomplete
    _check_type: Incomplete
    errors: list[str]
    results: ParamList
    _no_fix: bool
    def __init__(self, name: str, check_type: CheckType, pl: ParamList | None = None, p: Param | None = None) -> None: ...
    def __repr__(self) -> str: ...
    @property
    def has_errors(self) -> bool: ...
    def adjust_params(self, *args, **kwargs) -> None: ...
    def no_fix(self) -> TypeData: ...
    def as_fix_method(self, prefix: str = 'Expected', postfix: str = '') -> str: ...
    def check_types(self, *args, **kwargs) -> bool: ...
    def check_return_value(self, rv: Any, prefix: str | None = None, postfix: str = '') -> bool: ...
