from _typeshed import Incomplete
from typing import Any

class _ValueIgnore:
    def __repr__(self) -> str: ...
    def __deepcopy__(self, memo: Any) -> _ValueIgnore: ...
    def __copy__(self) -> _ValueIgnore: ...

ValueIgnore: Incomplete

class TypeIgnore:
    value: Incomplete
    def __init__(self, value: Any) -> None: ...
    def __eq__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...

class IValueEqual:
    def __eq__(self, other: Any) -> bool: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...

def stringify(value: Any) -> str: ...
def type_name(t: Any) -> str: ...

_prefixes: Incomplete

def name_with_prefix(name: str, kind: Any) -> str: ...
