from _typeshed import Incomplete
from typing import Any

class _ValueIgnore: ...

ValueIgnore: Incomplete

class TypeIgnore:
    value: Incomplete
    def __init__(self, value: Any) -> None: ...
    def __eq__(self, other: Any) -> bool: ...

class IValueEqual:
    def __eq__(self, other: Any) -> bool: ...
    def __ne__(self, other: Any) -> bool: ...

def stringify(value: Any) -> str: ...
def type_name(t: Any) -> str: ...
def name_with_prefix(name: str, kind: Any) -> str: ...
